<?php declare(strict_types=1);

/**
 * Copyright (C) Brian Faust
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cline\Mint\Conductors;

use Cline\Mint\Enums\IdentifierType;
use Cline\Mint\Generators\Cuid2Generator;
use Cline\Mint\MintManager;
use Cline\Mint\Support\Identifiers\Cuid2;

/**
 * Fluent conductor for CUID2 generation and parsing.
 *
 * CUID2 is the successor to CUID, providing collision-resistant unique
 * identifiers with improved security. Default length is 24 characters.
 *
 * ```php
 * $cuid2 = Mint::cuid2()->generate();
 * $cuid2 = Mint::cuid2()->length(32)->generate();
 * $parsed = Mint::cuid2()->parse($string);
 * ```
 *
 * @author Brian Faust <brian@cline.sh>
 * @psalm-immutable
 */
final readonly class Cuid2Conductor
{
    /**
     * Create a new CUID2 conductor instance.
     *
     * @param MintManager $manager Central manager instance that coordinates identifier
     *                             generation across the Mint library. Handles generator
     *                             instantiation, configuration management, and provides
     *                             access to the underlying generator implementations.
     * @param null|int    $length  Target length for generated CUID2 strings. Must be
     *                             between 2 and 32 characters. When null, the generator
     *                             uses its default length of 24 characters. Shorter lengths
     *                             reduce collision resistance but produce more compact IDs.
     */
    public function __construct(
        private MintManager $manager,
        private ?int $length = null,
    ) {}

    /**
     * Set the length of the generated CUID2 (2-32).
     *
     * Returns a new conductor instance with the specified length configuration.
     * CUID2 supports customizable lengths to balance between compactness and
     * collision resistance. Default is 24 characters.
     *
     * @param  int  $length Desired length for generated CUID2 strings (2-32)
     * @return self New conductor instance with updated length configuration
     */
    public function length(int $length): self
    {
        return new self($this->manager, $length);
    }

    /**
     * Generate a new CUID2.
     *
     * Creates a collision-resistant unique identifier with improved security
     * compared to the original CUID. Uses cryptographically secure random
     * number generation and entropy spreading.
     *
     * @return Cuid2 New CUID2 identifier object with the configured length
     */
    public function generate(): Cuid2
    {
        $config = [];

        if ($this->length !== null) {
            $config['length'] = $this->length;
        }

        /** @var Cuid2Generator $generator */
        $generator = $this->manager->getGenerator(IdentifierType::Cuid2, $config);

        return $generator->generate();
    }

    /**
     * Parse a CUID2 string.
     *
     * Converts a CUID2 string representation into a CUID2 object for inspection
     * and manipulation. Validates the string format before parsing.
     *
     * @param  string $value CUID2 string to parse
     * @return Cuid2  Parsed CUID2 identifier object
     */
    public function parse(string $value): Cuid2
    {
        /** @var Cuid2Generator $generator */
        $generator = $this->manager->getGenerator(IdentifierType::Cuid2);

        return $generator->parse($value);
    }

    /**
     * Check if a string is a valid CUID2.
     *
     * Validates whether a given string conforms to the CUID2 format specification.
     * Does not verify if the CUID2 was actually generated by this system.
     *
     * @param  string $value String to validate
     * @return bool   True if the string is a valid CUID2 format, false otherwise
     */
    public function isValid(string $value): bool
    {
        return $this->manager->getGenerator(IdentifierType::Cuid2)->isValid($value);
    }
}
